[build]
  command = "ng build --base-href /anshu-kumar-portfolio/"
  publish = "dist/portfolio/browser"
  base = ""

[build.environment]
  NODE_VERSION = "14"
  NPM_VERSION = "6"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
